version: '3.7'

services:
  collect-mongodb-primary:
    image: 'bitnami/mongodb:latest'
    container_name: collect-mongodb-primary
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME}
      MONGODB_ROOT_USER: ${MONGODB_ROOT_USER}
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_REPLICA_SET_KEY: ${MONGODB_REPLICA_SET_KEY}
    volumes:
      - 'mongodb_master_data:/bitnami'
    ports:
      - ${MONGODB_PRIMARY_PORT}:27017
    networks:
      - gateway

  collect-mongodb-secondary:
    container_name: collect-mongodb-secondary
    image: 'bitnami/mongodb:latest'
    depends_on:
      - collect-mongodb-primary
    environment:
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME}
      ALLOW_EMPTY_PASSWORD: "yes"
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_INITIAL_PRIMARY_HOST: collect-mongodb-primary
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_REPLICA_SET_KEY: ${MONGODB_REPLICA_SET_KEY}
    networks:
      - gateway
    ports:
      - ${MONGODB_SECONDARY_PORT}:27017

  collect-mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    container_name: collect-mongodb-arbiter
    depends_on:
      - collect-mongodb-primary
    environment:
      MONGODB_REPLICA_SET_MODE: arbiter
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME}
      MONGODB_REPLICA_SET_KEY: ${MONGODB_REPLICA_SET_KEY}
      MONGODB_INITIAL_PRIMARY_HOST: collect-mongodb-primary
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - gateway
    ports:
      - ${MONGODB_ARBITER_PORT}:27017

  collect-mongodb-client:
    image: mongoclient/mongoclient
    container_name: collect-mongodb-client
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    networks:
      - gateway
    ports:
      - ${MONGODB_CLIENT_PORT}:3000
    depends_on:
      - collect-mongodb-primary


networks:
  gateway:
    external: true
    name: gateway

volumes:
  mongodb_master_data:
    driver: local
