version: '3.7'

services:
  cbe-static:
    container_name: cbe-static
    build:
      context: .
      dockerfile: ./apps/static/Dockerfile
      target: development
    command: npm run start:dev static
    env_file:
      - ./apps/static/.env
    depends_on:
      - cbe-mongodb-primary
      - cbe-mongodb-secondary
      - cbe-mongodb-arbiter
      - cbe-auth
      - cbe-rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
  cbe-auth:
    container_name: cbe-auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '8081:8081'
    env_file:
      - ./apps/auth/.env
    depends_on:
      - cbe-mongodb-primary
      - cbe-mongodb-secondary
      - cbe-mongodb-arbiter
      - cbe-rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  cbe-rabbitmq:
    image: rabbitmq
    container_name: cbe-rabbitmq
    ports:
      - '5672:5672'
  cbe-mongodb-primary:
    image: bitnami/mongodb:latest
    container_name: cbe-mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=cbe-mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'cbe_mongodb_master_data:/bitnami/mongodb'
    ports:
      - '27017:27017'

  cbe-mongodb-secondary:
    image: bitnami/mongodb:latest
    container_name: cbe-mongodb-secondary
    depends_on:
      - cbe-mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=cbe-mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=cbe-mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  cbe-mongodb-arbiter:
    image: bitnami/mongodb:latest
    container_name: cbe-mongodb-arbiter
    depends_on:
      - cbe-mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=cbe-mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=cbe-mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  cbe_mongodb_master_data:
