version: '3.7'

services:
  cbe-static:
    container_name: cbe-static
    build:
      context: .
      dockerfile: ../apps/static/Dockerfile
      target: development
    command: npm run start:dev static
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    env_file:
      - ../.env
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
  cbe-auth:
    container_name: cbe-auth
    build:
      context: .
      dockerfile: ../apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    ports:
      - '8081:8081'
    env_file:
      - ../.env
    volumes:
      - ../:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - cbe-msg-broker
      - cbe-db

  cbe-users:
    container_name: cbe-users
    build:
      context: .
      dockerfile: ../apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    ports:
      - '8083:8083'
    env_file:
      - ../.env
    volumes:
      - ../:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - cbe-msg-broker
      - cbe-db
networks:
  cbe-msg-broker:
    driver: bridge
  cbe-db:
    driver: bridge
