version: '3.7'

services:
  cbe-rabbitmq:
    image: rabbitmq
    container_name: cbe-rabbitmq
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    ports:
      - '5672:5672'
networks:
  default:
    name: cbe-msg-broker
